*&---------------------------------------------------------------------*
*& INCLUDE               ZZCOMR_TABLE_CREATE_CAL
*&---------------------------------------------------------------------*


*----------------------------------------------------------------------*
*       Class ZGO_CL_EVENT_RECEIVER Definition
*----------------------------------------------------------------------*
*
*----------------------------------------------------------------------*
CLASS ZGO_CL_EVENT_RECEIVER DEFINITION.
  PUBLIC SECTION.
    " Define Hostpot When Click
    METHODS HANDLE_HOTSPOT_CLICK
      FOR EVENT HOTSPOT_CLICK OF CL_GUI_ALV_GRID
      IMPORTING E_ROW_ID E_COLUMN_ID.

    METHODS HANDLE_DOUBLE_CLICK_TABLE
      FOR EVENT DOUBLE_CLICK OF CL_GUI_ALV_GRID
      IMPORTING E_ROW E_COLUMN.

    METHODS HANDLE_DOUBLE_CLICK_TABLE_FIEL
      FOR EVENT DOUBLE_CLICK OF CL_GUI_ALV_GRID
      IMPORTING E_ROW E_COLUMN.

    METHODS HANDLE_DOUBLE_CLICK_ELEMENT
      FOR EVENT DOUBLE_CLICK OF CL_GUI_ALV_GRID
      IMPORTING E_ROW E_COLUMN.

    METHODS HANDLE_DOUBLE_CLICK_DOMAIN
      FOR EVENT DOUBLE_CLICK OF CL_GUI_ALV_GRID
      IMPORTING E_ROW E_COLUMN.

    METHODS HANDLE_TOOLBAR_TABLE
      FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID
      IMPORTING E_OBJECT E_INTERACTIVE.

    METHODS HANDLE_TOOLBAR_TABLE_FIELD
      FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID
      IMPORTING E_OBJECT E_INTERACTIVE.

    METHODS HANDLE_TOOLBAR_ELEMENT
      FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID
      IMPORTING E_OBJECT E_INTERACTIVE.

    METHODS HANDLE_TOOLBAR_DOMAIN
      FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID
      IMPORTING E_OBJECT E_INTERACTIVE.


    METHODS HANDLE_COMMAND
      FOR EVENT USER_COMMAND OF CL_GUI_ALV_GRID
      IMPORTING E_UCOMM.
ENDCLASS.                    "ZGO_CL_EVENT_RECEIVER DEFINITION

*----------------------------------------------------------------------*
*       CLASS CL_EVENT_RECEIVER IMPLEMENTATION
*----------------------------------------------------------------------*
*
*----------------------------------------------------------------------*
CLASS ZGO_CL_EVENT_RECEIVER IMPLEMENTATION.
  " event when click the link
  METHOD HANDLE_HOTSPOT_CLICK.
    CONDENSE E_ROW_ID     NO-GAPS.
    CONDENSE E_COLUMN_ID  NO-GAPS.
    "MESSAGE TEXT-T06 TYPE 'I' DISPLAY LIKE 'W'.
  ENDMETHOD.                    "HANDLE_HOTSPOT_CLICK

  " event when double click
  METHOD HANDLE_DOUBLE_CLICK_TABLE.
    CONDENSE E_ROW     NO-GAPS.
    CONDENSE E_COLUMN  NO-GAPS.
  ENDMETHOD.                    "HANDLE_DOUBLE_CLICK

  " event when double click
  METHOD HANDLE_DOUBLE_CLICK_TABLE_FIEL.
    CONDENSE E_ROW     NO-GAPS.
    CONDENSE E_COLUMN  NO-GAPS.
  ENDMETHOD.                    "HANDLE_DOUBLE_CLICK

  " event when double click
  METHOD HANDLE_DOUBLE_CLICK_ELEMENT.
    CONDENSE E_ROW     NO-GAPS.
    CONDENSE E_COLUMN  NO-GAPS.
  ENDMETHOD.                    "HANDLE_DOUBLE_CLICK

  " event when double click
  METHOD HANDLE_DOUBLE_CLICK_DOMAIN.
    CONDENSE E_ROW     NO-GAPS.
    CONDENSE E_COLUMN  NO-GAPS.
  ENDMETHOD.                    "HANDLE_DOUBLE_CLICK


  " Toolbar
  METHOD HANDLE_TOOLBAR_TABLE.

    PERFORM FRM_ADD_BUTTON TABLES E_OBJECT->MT_TOOLBAR USING 'CREATE_TABLE'   ICON_CREATE TEXT-T11 0 '' TEXT-T20.

  ENDMETHOD.                    "HANDLE_TOOLBAR

  " Toolbar Table Field
  METHOD HANDLE_TOOLBAR_TABLE_FIELD.

    PERFORM FRM_ADD_BUTTON TABLES E_OBJECT->MT_TOOLBAR USING 'SHOW_ALL_TABLE_FILED'   ICON_CONVERT_ALL TEXT-T10 0 '' TEXT-T20.
    "PERFORM FRM_ADD_BUTTON TABLES E_OBJECT->MT_TOOLBAR USING 'CREATE_TABLE'           ICON_CREATE      TEXT-T11 0 '' TEXT-T21.

  ENDMETHOD.                    "HANDLE_TOOLBAR

  " Toolbar Element
  METHOD HANDLE_TOOLBAR_ELEMENT.

    "PERFORM FRM_ADD_BUTTON TABLES E_OBJECT->MT_TOOLBAR USING 'SHOW_ALL_ELEMENT'   ICON_CONVERT_ALL TEXT-T10 0 '' TEXT-T20.
    PERFORM FRM_ADD_BUTTON TABLES E_OBJECT->MT_TOOLBAR USING 'CREATE_ELEMENT'     ICON_CREATE      TEXT-T12 0 '' TEXT-T22.

  ENDMETHOD.                    "HANDLE_TOOLBAR

  " Toolbar Domain
  METHOD HANDLE_TOOLBAR_DOMAIN.

    "PERFORM FRM_ADD_BUTTON TABLES E_OBJECT->MT_TOOLBAR USING 'SHOW_ALL_DOMAIN'   ICON_CONVERT_ALL TEXT-T10 0 '' TEXT-T20.
    PERFORM FRM_ADD_BUTTON TABLES E_OBJECT->MT_TOOLBAR USING 'CREATE_DOMAIN'     ICON_CREATE      TEXT-T13 0 '' TEXT-T23.

  ENDMETHOD.                    "HANDLE_TOOLBAR

  " 实现USER-COMMAND 事件方法
  METHOD HANDLE_COMMAND.

    DATA:LV_TYPE TYPE C,
         LV_MESSAGE TYPE STRING.


    CASE E_UCOMM.
      WHEN 'SHOW_ALL_TABLE_FILED'.
        PERFORM FRM_SHOW_ALL_TABLE_FILED.
      WHEN 'SHOW_ALL_ELEMENT'.
        PERFORM FRM_SHOW_ALL_ELEMENT.
      WHEN 'SHOW_ALL_DOMAIN'.
        PERFORM FRM_SHOW_ALL_DOMAIN.
      WHEN 'CREATE_TABLE'.
        PERFORM FRM_CREATE_TABLE CHANGING LV_TYPE LV_MESSAGE..
      WHEN 'CREATE_ELEMENT'.
        PERFORM FRM_CREATE_ELEMENT CHANGING LV_TYPE LV_MESSAGE.
      WHEN 'CREATE_DOMAIN'.
        PERFORM FRM_CREATE_DOMAIN CHANGING LV_TYPE LV_MESSAGE.
    ENDCASE.
  ENDMETHOD.                    "HANDLE_COMMAND

ENDCLASS.                    "CL_EVENT_RECEIVER IMPLEMENTATION


DATA: GO_EVENT_RECEIVER TYPE REF TO ZGO_CL_EVENT_RECEIVER.